### np.array()

In [2]:
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

### np.zeros()

In [3]:
np.zeros((5,), dtype=int)


array([0, 0, 0, 0, 0])

In [4]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

### np.ones()

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
s = (2,2)
np.ones(s)

array([[1., 1.],
       [1., 1.]])

### np.full()

In [10]:
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [9]:
np.full((2, 2), [1, 2])

array([[1, 2],
       [1, 2]])

### np.ravel()

In [11]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

### np.dot()

In [12]:
np.dot(3, 4)

12

In [14]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

### np.concatenate()

In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### np.vstack()

In [16]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### np.where()

In [17]:
a = np.arange(10)
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

### np.std()

In [18]:
a = np.array([[1, 2], [3, 4]])
np.std(a)

1.118033988749895

### np.max()

In [19]:
a = np.arange(4).reshape((2,2))
'''
([[0, 1],
[2, 3]])
'''
np.max(a)

3

### np.argmax()

In [20]:
a = np.arange(6).reshape(2,3) + 10
'''
([[10, 11, 12],
[13, 14, 15]])
'''
np.argmax(a)

5

### np.eye()

In [21]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [22]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

### np.arange()

In [24]:
np.arange(3,7)

array([3, 4, 5, 6])

### np.linspace()

In [25]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [26]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

### np.reshape()

In [28]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

### np.transpose()

In [29]:
a = np.array([[1, 2], [3, 4]])
'''
([[1, 2],
[3, 4]])
'''
np.transpose(a)

array([[1, 3],
       [2, 4]])

### np.cross()

In [30]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

### np.split()

In [34]:
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

### np.hstack()

In [35]:
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

### np.mean()

In [36]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

### np.min()

In [37]:
a = np.arange(4).reshape((2,2))
'''
([[0, 1],
[2, 3]])
'''
np.min(a)

0

### np.argmin()

In [40]:
a = np.arange(6).reshape(2,3) + 10
'''
([[10, 11, 12],
[13, 14, 15]])
'''
np.argmin(a)

0

### np.unique()

In [41]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [42]:
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, axis=0)

array([[1, 0, 0],
       [2, 3, 4]])